config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :resumes do
    collection do
      get :my
    end

    member do
      patch :pin
    end
  end
  # 上面這行等於下面八行
  # get "/resumes", to: "resumes#index"
  # get "/resumes/new", to: "resumes#new", as: "new_resume"
  # post "/resumes", to: "resumes#create"
  # get "/resumes/:id", to: "resumes#show", as: "resume"
  # delete "/resumes/:id", to: "resumes#destroy"
  # get "/resumes/:id/edit", to: "resumes#edit", as: "edit_resume"
  # patch "/resumes/:id", to: "resumes#update"
  # put "/resumes/:id", to: "resumes#update"
  
  resource :users, only: [:create] do
    get :sign_up
    get :sign_in
  end
  # 可以把下面這兩行包進去，因為sing_up是我們自定義的名字，所以是用個block包，而creat是本來resource就會產生的路徑之一，所以寫在上面
  # get "/users/sign_up", to: "users#new"
  # post "/users/", to: "users#create"

  resource :sessions, only: [:create, :destroy] do
  end
  # 其實要建立在users的resource也是可以

  get "/@:user_id", to: "users#default_resume"
  get "/@:user_i/:id", to: "resumes#show", as: "user_resume"

  root "resumes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
  extend FriendlyId
  friendly_id :random_slug, use: :slugged
  # -> slug

  has_one_attached :photo

  validates :title, presence: true
  validates :content, presence: true


  # scope :published -> {}
  scope :published, -> { where(status: "published") }
  scope :draft, -> { where(status: "draft") }

  # relationships
  belongs_to :user

  def self.all_status
    [
      ["草稿", "draft"], 
      ["發布", "published"],
    ]
  end

  private
    def random_slug # 把網址上的履歷編號變亂數
      [*"0".."9", *"a".."z", "-", "_"].sample(10).join
    end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :password, 
             presence: true, 
             confirmation: true, 
             length: { minimum: 6}

  # relationships           
  has_many :resumes

  # callbacks
  before_create :encrypt_password

  def self.login(user_data)
    account = user_data[:account]
    password = user_data[:password]

    if account && password
      user = find_by("email = ? OR username = ?", account, account)
      if user && user.password == HelloKitty::Encoder.encode_password(password)
        user
      else
        nil
      end
    else
      nil
    end
  end

  def default_resume
    resumes.last
  end

  private
    def encrypt_password
      self.password = HelloKitty::Encoder.encode_password(self.password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  helper_method :user_signed_in?, :current_user

  private
    def user_signed_in?
      session[:thankyou9527].present?
    end  

    def not_found
      render file: "#{Rails.root}/public/404.html",
             status: 404
    end

    def current_user
      User.find_by(id: session[:thankyou9527])
    end

    def authenticate_user
      if not user_signed_in?
        redirect_to sign_in_users_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :find_resume, only: [:show]
  before_action :find_my_resume, only: [:destroy, :edit, :update, :pin]
  before_action :authenticate_user, expect: [:index, :show]

  def index
    # render html: current_user
    # 如果是.all就會顯示全部的（包括草稿狀態的）
    @resumes = Resume.published
  end

  def new
    @resume = Resume.new
  end

  def create
    # @resume = Resume.new(resume_params)
    # @resume = user_id = current_user.id
    @resume = current_user.resumes.new(resume_params)

    if @resume.save
      # flash[:notice] = "新增成功"
      redirect_to my_resumes_path, notice: "新增成功"
    else
      render action: :new #這邊是借new.erb那個檔案來渲染 並非走回第五行
    end
  end

  def show
  end

  def destroy
    @resume.destroy
    redirect_to resumes_path, notice: "已刪除"
  end

  def edit
  end

  def update
    if @resume.update(resume_params)
      redirect_to my_resumes_path, notice: "修改成功"
    else
      render action: :edit #這邊是借edit.erb那個檔案來渲染
    end
  end

  def my
    @resumes = current_user.resumes
  end

  def pin
    current_user.resumes.update_all("pinned = false")
    @resume.update(pinned: true)
    redirect_to my_resumes_path, notice: "預設履歷設定成功"
  end

  private
    def resume_params
      params.require(:resume).permit(:title, :content, :status, :photo)
    end

    def find_resume
      if user_signed_in?
        @resume = current_user.resumes.friendly.find(params[:id])
      else
        @resume = Resume.pulished.friendly.find(params[:id])
      end
    end

    def find_my_resume
      @resume = current_user.resumes.friendly.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # 檢查帳號密碼是否存在
    user = User.login(params[:user])
    if user
      # 發 session
      session[:thankyou9527] = user.id
      redirect_to root_path, notice: "登入成功"
    else
      redirect_to sign_in_users_path, alert: "帳號密碼有誤"
    end
  end

  def destroy
    session[:thankyou9527] = nil
    redirect_to root_path, notice: "已登出"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "會員註冊成功"
    else
      render :sign_up
    end
  end

  def sign_in 
  end

  def default_resume
    @user = User.find_by!(username: params[:user_id])
    @resume = @user.default_resume
  end

  private
    def user_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
    def markdown(content)
      tag.artical data: { controller: "markdown-viewer" } do
        content
      end
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # def user_signed_in?
  #   !session[:thankyou9527].nil?
  # end

  # def current_user
  #   User.find_by(id: session[:thankyou9527])
  # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyResume</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" if flash %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello, World</h1>

app/views/resumes/_form.html.erb
<%= form_with(model: resume) do |form| %>
  <div class="fields">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title, autocomplete: "off", autocus: true %>
</div>

<div class="fields">
<%= form.label :photo, "照片" %>
<%= form.file_field :photo %>
</div>

<div class="fields-content">
  <%= form.label :content, "內容" %>
  <%= form.text_area :content, data: { controller: "markdown-editor" } %>
</div>
<div class="fields">
  <%= form.label :status, "狀態" %>
  <%= form.select :status, Resume.all_status %>
</div>
<%= form.submit %>
<% end %>

app/views/resumes/_resume.html.erb
  <li>
    <%= "v" if resume.pinned %>
    <%= link_to resume.title, user_resume_path(user_i: resume.user.username, id: resume.slug) %>
    |
    <%= link_to "預", pin_resume_path(resume), method: :patch %>
    |
    <%= link_to "X", resume_path(resume), method: :delete, data: {
        confirm: "確定要刪除嗎？"
    } %>
    <!-- <%= link_to resume.title, resume_path(resume) %>
    <%= link_to resume.title, resume %> -->
  </li>

app/views/resumes/edit.html.erb
<h1>編輯履歷</h1>

<%= render "form", resume: @resume %>

app/views/resumes/index.html.erb
<h1>Resume</h1>

<ul>
  <%= render @resumes %>
</ul>

app/views/resumes/my.html.erb
<h1>我的履歷</h1>

<%= link_to "新增履歷", new_resume_path %>

<ul>
  <%= render @resumes %>
</ul>

app/views/resumes/new.html.erb
<h1>新增履歷</h1>

<%= form_with(model: @resume) do |form| %>
  <div class="fields">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title, autocomplete: "off", autocus: true %>
</div>
<div class="fields">
  <%= form.label :content, "內容" %>
  <%= form.text_area :content %>
</div>
<div class="fields">
  <%= form.label :status, "狀態" %>
  <%= form.select :status, Resume.all_status %>
</div>
<%= form.submit %>
<% end %>

app/views/resumes/show.html.erb
<h1><%= @resume.title %> 履歷</h1>
<%= link_to "修改", edit_resume_path(@resume) %>

<%= image_tag @resume.photo if @resume.photo.attached? %>

<%= markdown(@resume.content) %>

<!--這串配合模組改寫成上面那行
 <article data-controller="markdown-viewer">
  <%= @resume.content %>
</article> -->

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div data-controller="flash" class="flash flash-<%= type %>">
    <div><%= message %></div>
    <button id="flashCloseBtn" data-action="click->flash#close">X</button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav">
    <div class="brand"><%= link_to "厲害的履歷", root_path %></div>
    <ul>
    <% if user_signed_in? %>
    <li><%= current_user.email %></li>
    <li class="signin"><%= link_to "我的履歷", my_resumes_path %></li>
    <li class="signin"><%= link_to "登出", sessions_path, method: "delete" %></li>
    <% else %>
        <li class="signup"><%= link_to "註冊", sign_up_users_path%></li>
        <li class="signin"><%= link_to "登入", sign_in_users_path %></li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/users/default_resume.html.erb
<h1><%= @user.username %></h1>
<%= markdown(@resume.content) %>

app/views/users/new.html.erb
<h1>會員註冊</h1>

<%= form_with(model: @user, url: "/users", method: "post") do |form| %>
  <div class="fields">
      <%= form.label :email %>
      <%= form.email_field :email, autocomplete: "off" %>
  </div>
  <div class="fields">
      <%= form.label :username %>
      <%= form.text_field :username, autocomplete: "off" %>
  </div>
  <div class="fields">
      <%= form.label :password %>
      <%= form.password_field :password %>
  </div>
  <div class="fields">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
  </div>
  <%= form.submit %>
<% end %>

app/views/users/sign_in.html.erb
<h1>會員登入</h1>

<%= form_with(url: sessions_path, scope: "user", method: "post") do |form| %>
  <div class="fields">
      <%= form.label :account, "帳號" %>
      <%= form.text_field :account, autocomplete: "off", placeholder: "請輸入 e-mail 或 username " %>
  </div>
  <div class="fields">
      <%= form.label :password, "密碼" %>
      <%= form.password_field :password %>
  </div>
  <%= form.submit "登入" %>
<% end %>

app/views/users/sign_up.html.erb
<h1>會員註冊</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do | message | %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @user) do |form| %>
  <div class="fields">
      <%= form.label :email %>
      <%= form.email_field :email, autocomplete: "off" %>
  </div>
  <div class="fields">
      <%= form.label :username %>
      <%= form.text_field :username, autocomplete: "off" %>
  </div>
  <div class="fields">
      <%= form.label :password %>
      <%= form.password_field :password %>
  </div>
  <div class="fields">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
  </div>
  <%= form.submit %>
<% end %>